import React from 'react'
import Footer from '../Fotter'
import { useNavigate } from 'react-router-dom'

export default function About() {
  const navigate = useNavigate()
  const goForm= ()=>{
    navigate('/MadeMeResume')
  }
  return (
    <>
      <div className='containerPageAbout'>
        <div className='containerHero'>
          <div> <section class="hero">
            <div class="intro-text">
              <h1>
                <span class="hear"> Create your winning resume in just 10 minutes </span> <br />
              </h1>
              <ul className='listOptions'>
                <li>
                  <strong>AI Powerful resume builder </strong> with tested beautiful templates
                </li>
                <li>
                  <strong>Easier and faster</strong> than a conventional editor
                </li>
                <li>

                  Advice of professionals to <strong>get hired faster!</strong>
                </li>
              </ul>
              <p class="btn red" href="#">CHOOSE A TEMPLATE</p>

            </div>
            <div class="i-frame">
              <iframe
                width="560"
                height="315"
                src="https://www.youtube.com/embed/u75hUSShvnc"
                title="YouTube video player"
                frameborder="10"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              ></iframe>
              <div class="stand-1"></div>
              <div class="stand-2"></div>
            </div>
          </section></div>
        </div>
        <div className='containerSteps'>
          <div>
            <h1>Get your professional resume in 3 steps</h1>
          </div>
          <div className='steps'>
            <div className='step1'>
              <img src="https://static.resumecoach.com/wp-content/uploads/sites/43/2024/01/11112535/1_choose_ATS.png" alt="" />
              <h3>Choose a template optimized for ATS</h3>
            </div>
            <div className='step2'>
              <img src="https://static.resumecoach.com/wp-content/uploads/sites/43/2024/01/11112537/2_AI.png" alt="" />
              <h3>Complete with phrases generated by the assistant</h3>
            </div>
            <div className='step3'>
              <img src="https://static.resumecoach.com/wp-content/uploads/sites/43/2024/01/11112538/3_download.png" alt="" />
              <h3>Provide the right format, download, and send</h3>
            </div>
          </div>
        </div>
        <div className='BuiltResume'>
          <p onClick={goForm} class="btn red " href="#">BUILT MY RESUME</p>
        </div>
      </div>
    <Footer/>
    </>


  )
}
